name: jivosdk
description: Flutter plugin that bridges to JivoSDK
version: 1.1.0
homepage: https://www.jivosite.com/

environment:
  sdk: '>=3.2.5 <4.0.0'
  flutter: ">=3.19.0"

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.1.8
  firebase_core: ^4.1.1
  firebase_messaging: ^16.0.2

flutter:
  plugin:
    platforms:
      android:
        package: com.jivosite.jivosdk_plugin
        pluginClass: JivoPlugin
      ios:
        pluginClass: JivoPlugin
